image: tmaier/docker-compose:latest

services:
  - docker:dind

before_script:
  - docker info
  - docker-compose --version
  - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" $CI_REGISTRY

build_backend:
  stage: build
  tags:
    - docker
  script:
    - docker-compose build

test_backend:
  stage: test
  tags:
    - docker
  script:
    - docker-compose -f docker-compose.tests.yml up -d
    - sleep 15
    - docker-compose exec -T backend pytest -p no:warnings --cov=. --cov-report html
    - docker-compose exec -T backend coverage report --omit=things_that_arent_mine/* --precision=2

deploy_backend:
  stage: deploy
  tags:
    - docker
  script:
    - echo "Deploy script go here"
