version: '3.8'

services:
  nginx:
    build: ./nginx
    ports:
      - 1337:80
    depends_on:
      - backend
  emulate:
    build:
      context: .
      dockerfile: ./EmulateDockerfile
    command: ["python3", "emulate_queue.py"]
    restart: always
    env_file:
      - ./emulate/.env.dev
    depends_on:
      - redis
      - backend
  sender:
    build:
      context: .
      dockerfile: ./EmulateDockerfile
    command: ["python3", "sender.py"]
    ports:
      - 5678:5678
    restart: always
    env_file:
      - ./emulate/.env.dev
    depends_on:
      - redis
      - backend
  backend:
    build: ./backend
    command: >
      sh -c "python manage.py collectstatic --noinput &&
             python manage.py migrate &&
             python manage.py runserver 0.0.0.0:8000"
    expose:
      - 8000
    env_file:
      - ./backend/.env.dev
    depends_on:
      - database
      - redis
  celery:
    build: ./backend
    command: celery -A lights worker -l INFO
    volumes:
      - ./backend/:/user/src/app/
    depends_on:
      - redis
      - database
  database:
    image: postgres:9.6.21-alpine
    env_file:
      - ./backend/.env.dev
  redis:
    image: redis:6.2.1-alpine
